HAVE_DYNARRAY #compile test
HAVE_GCC #compile test
USE_THREADED_CODE #compile test
##HAVE_LIBREADLINE
HAVE_LIBSOCKET
HAVE_LIBNSL
# HAVE_LIBGMP
inline
##STDC_HEADERS
HOST_ALIAS
SUPPORT_CONDOR
USE_PTHREAD_LOCKING
##HAVE_SYS_WAIT_H
NO_UNION_WAIT
##HAVE_ALLOCA_H
# HAVE_ARPA_INET_H
#HAVE_CTYPE_H
#HAVE_CRYPT_H
HAVE_CUDD_H
HAVE_CUDDINT_H
HAVE_CUDD_CUDD_H
HAVE_CUDD_CUDDINT_H
HAVE_CUDD_UTIL_H
#HAVE_DIRECT_H
#HAVE_DIRENT_H
# HAVE_DLFCN_H
##HAVE_ERRNO_H
##HAVE_EXECINFO_H
##HAVE_FCNTL_H
##HAVE_FENV_H
##HAVE_FLOAT_H
##HAVE_FPU_CONTROL_H
# HAVE_GMP_H
##HAVE_IEEEFP_H
##HAVE_IO_H
##HAVE_LIMITS_H
##HAVE_LOCALE_H
# HAVE_MACH_O_DYLD_H
##HAVE_MALLOC_H
##HAVE_MATH_H
##HAVE_MEMORY_H
# HAVE_MPE_H
HAVE_MPI_H
# HAVE_NETDB_H
# HAVE_NETINET_IN_H
##HAVE_NETINET_TCP_H
HAVE_PTHREAD_H
##HAVE_PWD_H
HAVE_READLINE_READLINE_H
HAVE_READLINE_HISTORY_H
# HAVE_REGEX_H
HAVE_RINTERFACE_H
##HAVE_SIGINFO_H
##HAVE_SIGNAL_H
##HAVE_STDARG_H
##HAVE_STDINT_H
##HAVE_STRING_H
# HAVE_STROPTS_H
# HAVE_SYS_CONF_H
##HAVE_SYS_DIR_H
##HAVE_SYS_FILE_H
##HAVE_SYS_MMAN_H
##HAVE_SYS_NDIR_H
##HAVE_SYS_PARAM_H
##HAVE_SYS_RESOURCE_H
##HAVE_SYS_SELECT_H
##HAVE_SYS_SHM_H
# HAVE_SYS_SOCKET_H
##HAVE_SYS_STAT_H
##HAVE_SYS_TIME_H
##HAVE_SYS_TIMES_H
##HAVE_SYS_TYPES_H
##HAVE_SYS_UCONTEXT_H
# HAVE_SYS_UN_H
##HAVE_SYS_WAIT_H
##HAVE_TIME_H
##HAVE_UNISTD_H
##HAVE_UTIME_H
HAVE_UTIL_H
##HAVE_WCTYPE_H
# HAVE_WINSOCK_H
# HAVE_WINSOCK2_H
# HAVE_RESTARTABLE_SYSCALLS
# TM_IN_SYS_TIME
MALLOC_T #compile test

MinTrailSpace
MinStackSpace
MinHeapSpace
DefTrailSpace
DefStackSpace
DefHeapSpace
##RETSIGTYPE
##HAVE__CHSIZE_S
##HAVE__NSGETENVIRON
##HAVE_ACCESS
##HAVE_ACOSH
HAVE_ALARM
##HAVE_ALLOCA
##HAVE_ASINH
##HAVE_ATANH
# HAVE_CHDIR
##HAVE_CLOCK
##HAVE_CLOCK_GETTIME
# HAVE_CTIME
##HAVE_DLOPEN
# HAVE_DUP2
##HAVE_ERF
# HAVE_FECLEAREXCEPT
##HAVE_FESETTRAPENABLE
HAVE_FETESTEXCEPT
# HAVE_FGETPOS
##HAVE_FINITE
##HAVE_FPCLASS
##HAVE_FTIME
##HAVE_GETCWD
##HAVE_GETENV
# HAVE_GETHOSTBYNAME
# HAVE_GETHOSTENT
##HAVE_GETHOSTID
##HAVE_GETHOSTNAME
##HAVE_GETHRTIME
##HAVE_GETPAGESIZE
##HAVE_GETPWNAM
##HAVE_GETRLIMIT
##HAVE_GETRUSAGE
##HAVE_GETTIMEOFDAY
##HAVE_GETWD
##HAVE_ISATTY
##HAVE_ISINF
##HAVE_ISNAN
# HAVE_KILL
# HAVE_LABS
##HAVE_LGAMMA
##HAVE_LINK
##HAVE_LOCALTIME
##HAVE_LSTAT
##HAVE_MALLINFO
##HAVE_MBSCASECOLL
##HAVE_MBSCOLL
##HAVE_MBSNRTOWCS
##HAVE_MEMCPY
##HAVE_MEMMOVE
##HAVE_MKSTEMP
##HAVE_MKTEMP
##HAVE_MKTIME
HAVE_MMAP
##HAVE_NANOSLEEP
HAVE_NSLINKMODULE
##HAVE_OPENDIR
HAVE_POPEN
HAVE_PTHREAD_MUTEXATTR_SETKIND_NP
HAVE_PTHREAD_MUTEXATTR_SETTYPE
##HAVE_PUTENV
##HAVE_RAND
##HAVE_RANDOM
##HAVE_READLINK
##HAVE_REGEXEC
##HAVE_RENAME
##HAVE_RINT
# HAVE_RL_CLEAR_PENDING_INPUT
# HAVE_RL_CLEANUP_AFTER_SIGNAL
HAVE_RL_COMPLETION_MATCHES
HAVE_RL_EVENT_HOOK
HAVE_RL_FILENAME_COMPLETION_FUNCTION
# HAVE_RL_FREE_LINE_STATE
HAVE_RL_INSERT_CLOSE
HAVE_RL_SET_PROMPT
# HAVE_RL_STATE_INITIALIZED
# HAVE_SBRK
##HAVE_SELECT
##HAVE_SETBUF
##HAVE_SETITIMER
# HAVE_SETLINEBUF
##HAVE_SETLOCALE
##HAVE_SETSID
# HAVE_SHMAT
##HAVE_SIGACTION
# HAVE_SIGGETMASK
# HAVE_SIGINTERRUPT
##HAVE_SIGNAL
##HAVE_SIGPROCMASK
HAVE_SIGSETJMP
HAVE_SLEEP
HAVE_SNPRINTF
# HAVE_SOCKET
##HAVE_STAT
# HAVE_STRCHR
##HAVE_STRERROR
##HAVE_STRICMP
##HAVE_STRLWR
##HAVE_STRNCAT
##HAVE_STRNCPY
# HAVE_STRTOD
HAVE_SYSTEM
##HAVE_TIME
##HAVE_TIMES
##HAVE_TMPNAM
# HAVE_TTYNAME
##HAVE_USLEEP
##HAVE_UTIME
##HAVE_VSNPRINTF
HAVE_WAITPID
HAVE_MPZ_XOR
HAVE_SIGINFO
HAVE_SIGSEGV
HAVE_SIGPROF
HAVE_ENVIRON
HAVE_VAR_TIMEZONE
HAVE_STRUCT_TIME_TM_GMTOFF
HAVE_VAR_TIMEZONE
HAVE_STRUCT_TIME_TM_GMTOFF
USE_DL_MALLOC
USE_MALLOC
USE_SYSTEM_MALLOC
FORCE_SECOND_QUADRANT
_XOPEN_SOURCE
# BROKEN_FFLUSH_NULL
HAVE_GCC
GC_NO_TAGS
MAX_WORKERS
MAX_THREADS
##USE_GMP